### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by gauravrupamrai** [eli64s/readme-ai-streamlit#1]
https://readmeai.streamlit.app/ is not working

Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/eli64s/readmeai-ui/issues/new).

**Comment by eli64s** [comment]
Hey, just rebooted the app. Should be up now.

**Comment by elorberb** [comment]
I think it is not working again.. getting this error message: 
![image](https://github.com/eli64s/readmeai-ui/assets/64037485/6ef53446-b24f-4a98-b6ca-5d95b7cec385)

**Comment by eli64s** [comment]
@elorberb it is back up now! Thank you.

**Comment by arielya10** [comment]
Not working again.
Any fix?

**Comment by eli64s** [comment]
@arielya10 please try again, I rebooted the Streamlit app.

**Comment by arielya10** [comment]
Thank you for the update. Still not working.
