### ISSUE TITLE
https://readmeai.streamlit.app not working

### ISSUE THREAD

**Issue by arielya10** [eli64s/readme-ai-streamlit#2]
I'm trying to reach your website, but I get an error:
Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/eli64s/readmeai-ui/issues/new).

**Comment by eli64s** [comment]
@arielya10 please try once again! Thank you for reporting.

**Comment by arielya10** [comment]
@eli64s It worked for a second and went off again.
