### ISSUE TITLE
Website down!

### ISSUE THREAD

**Issue by Aashish17405** [eli64s/readme-ai-streamlit#8]
I am unable to open the website. I am able to see this message:"Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/eli64s/readme-ai-streamlit/issues/new)."
![Screenshot 2024-08-24 144340](https://github.com/user-attachments/assets/e07646d2-6f77-4d0a-93e6-00fb4f1e7aea)

**Comment by eli64s** [comment]
@Aashish17405 Please check again, thank you!

https://readme-ai.streamlit.app/
