### ISSUE TITLE
The web of project is down

### ISSUE THREAD

**Issue by Zensi77** [eli64s/readme-ai-streamlit#9]
![Screenshot 2024-10-15 191927](https://github.com/user-attachments/assets/31c2b923-a20c-4ef5-8849-31791b9f0efe)

**Comment by eli64s** [comment]
@Zensi77 Thank you for bringing to my attention. It should be back up now!

**Comment by Zensi77** [comment]
It went when I tried it a while ago, but it fell off again

**Comment by eli64s** [comment]
@Zensi77 I've rebooted it once again, thank you.
